### ISSUE TITLE
Indian ip blocked

### ISSUE THREAD

**Issue by pk3011** [SharzyL/pastebin-worker#27]
Kindly fix it

**Comment by SharzyL** [comment]
Blocked as intended

**Comment by Misaka13514** [comment]
Today, I received a legal notice regarding copyright infringement from The Board of Control for Cricket in India (“BCCI”) because someone uploaded some pirated feeds of IPTV and distributed them widely.

While cleaning things up, I also discovered a few other potentially abusive activities. I'm sharing here only the ones I was able to detect.

- @SharzyL https://github.com/search?q=/http[s]?:\/\/(shz\.al)\//&type=code
- @Misaka13514 https://github.com/search?q=/http[s]?:\/\/(p\.apeiria\.net)\//&type=code
- @baddate https://github.com/search?q=/http[s]?:\/\/(pb\.oii\.im)\//&type=code
- @tg-jiedianxielou-mc https://github.com/search?q=/http[s]?:\/\/(pb\.jiedianxielou\.workers\.dev)\//&type=code

Since I’ve now blocked all access from Indian IP addresses for my fork, it's foreseeable that the path of least resistance for abusers will be to migrate to [other forks of this repository](https://github.com/SharzyL/pastebin-worker/forks). It might be worth reviewing your forks or applying similar restrictions if necessary.

**Comment by SharzyL** [comment]
After enforcing paste expiration, most of abused pastes are already expired. It remains to take care of automatically uploaded pastes.
